### ISSUE TITLE
Cannot read v8 schema using Altova XMLSpy

### ISSUE THREAD

**Issue by macumber** [tudelft3d/cityjson#34] opened 2018-11-15 03:10 UTC
Altova XMLSpy is a very useful tool for working with JSON files and JSON schemas.  When I load in the v8 CityJSON schema, Altova XMLSpy cannot follow the external schema links:

![xmlspy_68erxj17eq](https://user-images.githubusercontent.com/1327850/48527540-c8dcc100-e848-11e8-8a2e-6d59c1b0e9b1.png)

I am not sure if this is a limitation of XMLSpy or if the CityJSON schema is not correct.  Any of the following solutions would work for me:

1. Find another graphical schema editor (do you have any suggestions?)
1. Use a script to combine all the schema's together (does such a script exist?)
1. Change the CityJSON schema to meet Altova XMLSpy's requirements

Do you have any recommendations?

**Comment by kkimmy** [comment] 2018-11-15 13:00
This is a weird limitation/feature (whatever you wish to call it! :P) of XMLSpy. I had the same error/warning (unable to resolve the reference for "metadata.json" and so on) when I first used the XMLSpy for CityJSON. However, I was able to use XMLSpy to validate CityJSON datasets against the schema without any hassle. IMO, XMLSpy uses the path of "cityjson.json" schema as the base path for all other referenced schemas. So, you can validate a CityJSON dataset using XMLSpy if all your CityJSON schemas are within the same folder. If you delete any referenced schema (e.g. metadata.json) from the schema folder, XMLSpy will give you a validation error.

**Comment by hugoledoux** [comment] 2018-11-15 16:18
1. OxygenXML
2. not aware of any, I'm planning to write one at some point.
3. it ain't gonna happen :)

**Comment by macumber** [comment] 2018-11-16 06:38
Wow thanks for all the great activity on this ticket!

**Comment by hugoledoux** [comment] 2018-11-17 14:54
@macumber  stitching them into one is actually super easy: 

https://gist.github.com/hugoledoux/4002869e257c56341722f0302a37c73e

**Comment by macumber** [comment] 2018-11-21 17:13
Thanks @hugoledoux, not sure if you'd want to provide a single/minified schema with each release or not, Might be useful for people with limited JSON schema parsers.

**Comment by hugoledoux** [comment] 2018-11-22 08:59
@macumber good idea, I'll provide the merged one from next version.

but we have an implementation of the validation in [cjio](https://www.github.com/tudelft3d/cjio) that is ready to use, schemas are even included.

**Comment by afalk42** [comment] 2019-04-02 14:39
We have just released Altova XMLSpy v2019r3 today, which now supports draft-06 and draft-07 of JSON-Schema: [https://www.altova.com/xmlspy-xml-editor/whatsnew](https://www.altova.com/xmlspy-xml-editor/whatsnew)
Also, please note the following regarding the above issue:

- Our Text View works fine, i.e. editing support only where schemas are expected
- Validation works correctly, incl. resolution of references
- Schema editor handles named schema definitions correctly, only the error message/highlighting was misleading (and this has been fixed in the latest version)
- The only other graphical schema editor I am aware of is Liquid XML Studio (see [https://www.liquid-technologies.com/json-schema-editor](https://www.liquid-technologies.com/json-schema-editor)). I am not sure whether they resolve schema references graphically at all.
- OxygenXML does not provide any alternative (see [https://www.oxygenxml.com/doc/versions/20.1/ug-editorEclipse/topics/editing-JSON-schema.html](https://www.oxygenxml.com/doc/versions/20.1/ug-editorEclipse/topics/editing-JSON-schema.html))

**Comment by hugoledoux** [comment] 2019-06-19 14:15
the minified schema for 1.0.0 is available:
https://3d.bk.tudelft.nl/schemas/cityjson/1.0.0/cityjson.min.schema.json

it works fine with online apps like that one (https://json-schema-validator.herokuapp.com/) so should work for everything. All $ref have been removed.

**Comment by afalk42** [comment] 2019-06-19 14:44
Hi @hugoledoux 
The file you are referencing starts with:
`{"$schema":"http://json-schema.org/draft-04/schema#"`
so it is specifying draft-04. Therefore, XMLSpy 2019r3 will produce a series of warnings, because this schema file actually uses features of draft-07 already.
The fix is very easy - just specify the correct JSON schema version in the file:
`{"$schema":"http://json-schema.org/draft-07/schema#"`
Once you do that, XMLSpy will confirm that this file is valid!

**Comment by hugoledoux** [comment] 2019-06-19 14:46
What features from v07 is it using?

**Comment by afalk42** [comment] 2019-06-19 14:58
`"format": "date"`
and
`"format": "uri-reference"`
For further info, please see also: [https://json-schema.org/draft-07/json-schema-release-notes.html#formats](https://json-schema.org/draft-07/json-schema-release-notes.html#formats)

**Comment by hugoledoux** [comment] 2019-06-19 15:09
right, indeed. 

Just puzzled why my validation tests with dates and URIs were successful then... I use Python jsonschema validator (https://pypi.org/project/jsonschema/), and use v04 explicitly, see https://github.com/tudelft3d/cjio/blob/master/cjio/validation.py#L362

**Comment by hugoledoux** [comment] 2019-06-21 07:42
@afalk42 OK, I made some tests and all seems good with v07, and it's there: https://www.dropbox.com/s/t009xhvt1iiscji/cityjson.min.schema.json?dl=0

Can you confirm that it's fine in your software please?

My validator, jsonschema, processed correctly the time and uri even in v04... why I don't know.

**Comment by afalk42** [comment] 2019-06-21 08:28
@hugoledoux I can confirm that the new version you supplied via Dropbox works perfectly fine in XMLSpy v2019r3 now and is considered valid:

![Annotation 2019-06-21 102604](https://user-images.githubusercontent.com/6906332/59909116-3bc99e00-940f-11e9-9d68-8b677b13f530.png)

**Comment by hugoledoux** [comment] 2019-06-27 05:46
cheers, will be in v1.0.1

**Closed by hugoledoux** 2019-06-27 05:46 UTC
